# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: 
          java-version: 11
      - run: mvn -B package --file api/pom.xml
      - run: mkdir staging && cp api/target/*.jar staging
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging
      
  cd:
      runs-on: ubuntu-latest
      needs: ci
      steps:
        - uses: actions/checkout@v1
        - name: Docker login
          run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        - name: Build
          run: docker build -f api/Dockerfile -t api .
        - name: Tags
          run: | 
            docker tag api ${{ secrets.DOCKER_USER }}/api:${{ github.sha }}
            docker tag api ${{ secrets.DOCKER_USER }}/api:latest
        - name: Push
          run: |
            docker push ${{ secrets.DOCKER_USER }}/api:${{ github.sha }}
            docker push ${{ secrets.DOCKER_USER }}/api:latest
        
            
